### ISSUE TITLE
Improve scraping 'logistics'

### ISSUE THREAD

**Issue by kiliankoe** [offenesdresden/ParkAPI#10]
Specifically:
 - [x] Specify data as generically as possible in the city files (only config files would be too perfect, but probably not possible), so that they can easily be added without writing a python file that handles all the scraping and returns a finished dict
 - [x] Write a separate scraper that handles all the scraping and getting data in the correct format for *all* cities, so it won't be possible to have surprisingly differing output
 - [x] Dynamically import city files from the scraper
 - [x] Handle a database that scraper and server can talk to

For the time being the server will probably talk to the scraper directly, but the scraper should be able to run on it's own soon and store stuff into a database (I'm really liking the idea of just throwing the json into a mongodb instance - clear out #4 first though!), which the server then queries for current data. That way the scraper can run periodically (as easily as via cron) and the server only touches the previously saved data (usually the most current data) without them getting in each others way.

**Comment by JustusAdam** [comment]
## Suggestion

Instead of using beautiful soup, use regex to find the parking data.

This'll allow you to define a generic routine that fetches the data contained in the sites using regular expressions defined in a config file.

**Comment by kiliankoe** [comment]
As great as the idea of basically nothing more than a config file for each city sounds, I'm not ok with parsing HTML with regex. Far too much of a hassle.

**Comment by JustusAdam** [comment]
[well ...](https://github.com/JustusAdam/schedule-planner/blob/master/src/SchedulePlanner/Scraper/TUDresden.hs)

**Comment by JustusAdam** [comment]
I think it can work pretty well ...

**Comment by kiliankoe** [comment]
I stopped reading at line 6 where it says `Monad` :grin: 

But honestly, even it does work and would look far prettier implementation-wise, it would be a lot harder to maintain if sites change or random people want to add cities. 
The scraper is also not very dependent on performance (even though bs4 is pretty damn fast as it is), as it's supposed to be running every few minutes by itself and not serve data to the server.
