### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by kiliankoe** [offenesdresden/ParkAPI#103]
@florianschmidt1994 just wished for this :D

**Comment by sibbl** [comment]
Great idea! Would also love this as I'm too lazy to set all things up :+1:

**Comment by Manu1400** [comment]
Great idea! 👍

**Comment by jb3-2** [comment]
Great idea, I would love to get the server up and running without manual setup steps. Hasn't it already been done here (https://github.com/publicplan/ParkAPI/commit/d2bf77346b2b80f9c219c8cb1c8d22735d1b8c7e)? @Mechtecs does it work?

**Comment by Mechtecs** [comment]
Yes it works @jb3-2, it is used in production since I added it.

**Comment by jb3-2** [comment]
Wow, great! Could you maybe create a pull request towards the original repo so we can all profit from that easily? Thank you so much!

**Comment by jklmnn** [comment]
I have merged #171. Can you please check if everything works? We could the close this issue.

**Comment by jklmnn** [comment]
Since this seems to be fixed I'll close this issue. Reopen if required.

**Comment by kiliankoe** [comment]
The current Dockerfile has `live_scrape` set to `true`, which shouldn't be the case for actual production usage. This causes the application to fetch current data on every request to `/<city>`, potentially causing lots of unnecessary load on data providers.

**Comment by ylabonte** [comment]
We've opened a pull request for this.
