### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by kiliankoe** [offenesdresden/ParkAPI#12]
![](http://i.giphy.com/tZF2erGJ5uOHe.gif)

**Comment by Mic92** [comment]
Can strongly recommend a test library which replays https-request, for ruby I usually use vcr, probably this one could be a good fit https://github.com/kevin1024/vcrpy. Also speeds up development, because you have not to wait for network.

**Comment by kiliankoe** [comment]
Closing this in favor of #6.
