### ISSUE TITLE
Increase API version to 1.1

### ISSUE THREAD

**Issue by jklmnn** [offenesdresden/ParkAPI#126]
I recommend to increase the API version to 1.1 so clients can see if an attribution field is supplied or not (even though it is optional).
Due to the architecture, the attribution field is not omitted if no attribution is given but null, therefore the API version would flag the existence of this field.
This can surely be catched by clients but I think increasing the minor version is a more clean way.

See https://github.com/offenesdresden/ParkAPI/issues/125.

**Comment by kiliankoe** [comment]
Do we need semver on the API? Breaking changes would need a new version imho, but something new that won't break existing clients can just as well be thrown in there. Just my two cents.

**Comment by jklmnn** [comment]
Well the minor version would specify a minimum feature set. So 1.1 has all features that 1.0 has plus an additional feature. A client can say it needs 1.1, because it needs this feature but older clients can still use 1.1 since it includes all older features.

**Comment by kiliankoe** [comment]
Ok, why not. Go for it.

**Comment by kiliankoe** [comment]
Unless this breaks older clients relying on the version being specifically set to 1.0? Are we running both at the same time?

**Comment by jklmnn** [comment]
i have no idea :smile:

**Comment by kiliankoe** [comment]
Looks like I am, damn :D Please leave it at 1.0 for now^^ Will fix soon.

**Comment by kiliankoe** [comment]
please also see #140

**Comment by jklmnn** [comment]
Obsolete because of #140 and because nobody implements this yet.
