### ISSUE TITLE
Attribution for Denmark

### ISSUE THREAD

**Issue by jklmnn** [offenesdresden/ParkAPI#136]
@manuelciosici Thanks for the help again.
We have an attribution filed in our API and I think you should decide what we should enter as contributor to thank for your contribution.

**Comment by manuelciosici** [comment]
@jklmnn I looked at the JSON files for Zürich and Freiburg for examples of attribution. Can you explain what the license field covers? Is is the license of the underlying parking data, or the license of the contribution?

While we're at this, what is the role of the "active_support" field?

**Comment by jklmnn** [comment]
The license field covers the license of the underlying data. The contribution license currently would be MIT license, because thats what our code is licensed. If you wish something else, we have to look how we'd handle this.

Active support means, the data is kind of stable or we have the time to fix changes fast. Since all your data sources are APIs I'd recommend we set it to true (I don't expect those APIs to change soon or often).
For the user it means that he have to set an option to use "unstable" cities that might have  broken data or do not work at all. But I don't think thats an issue with your data.

If you have further questions, feel free to ask :)

**Comment by kiliankoe** [comment]
> For the user it means that he have to set an option to use "unstable" cities that might have broken data or do not work at all. But I don't think thats an issue with your data.

Those without `active_support` set to true are not shown by default in the mobile apps.

**Comment by jklmnn** [comment]
Voting: Set active_support to true for the current danish cities.

**Comment by manuelciosici** [comment]
Thank you. I have changed active_support to True, added myself as a contributor and added licenses where I could find them. All of the data is meant to be used publicly, but not all sources have mentions of licenses.

See pull request at https://github.com/offenesdresden/ParkAPI/pull/137

**Comment by jklmnn** [comment]
Thanks! I'll merge it and I think I'm going to get it online on the next days.
