### ISSUE TITLE
seperate data structure for geolocation

### ISSUE THREAD

**Issue by RobTranquillo** [offenesdresden/ParkAPI#14]
Instead of saving the geolocations inside of scraping-city.py should they stored in a seperate file to enable easy updating besides the automatic update while scraping a new parking-spot.

the new file should lay besides the scrape-city.py in /cities and should have the suffix .geo.
Like this:
..cities/
dresden.py
dresden.geo
Luebeck.py
Luebeck.geo

and the content should be like this:
{
        "Altmarkt": { "lat": 51.05031, "lon": 13.73754 },
        "An der Frauenkirche": { "lat": 51.05165, "lon": 13.7439} 
}

For later improvements we can change to geojson so github can render this file by it self on a map:
https://help.github.com/articles/mapping-geojson-files-on-github/

**Comment by kiliankoe** [comment]
All for it :+1:

**Comment by Mic92** [comment]
Should the extension be? `.geojson`

**Comment by kiliankoe** [comment]
It's soooo pretty :heart:

**Comment by kiliankoe** [comment]
Closing this as we now have geojson files from which the geodata for each city is read.
