### ISSUE TITLE
[Bonn] Data XML endpoint

### ISSUE THREAD

**Issue by sibbl** [offenesdresden/ParkAPI#151]
Hey all,

Bonn provides open data since 2014, which we could replace the current scraping solution with: http://www.bcp-bonn.de/stellplatz/bcpinfo.xml

Enum descriptions:
status: 0 = open, 1 = closed
tendenz: 1 = same, 2 = increasing, 3 = decreasing

Notes, including attribution: https://opendata.bonn.de/dataset/parkh%C3%A4user-parkhausbelegung

**Comment by kiliankoe** [comment]
Argh, I'm currently having fun rewriting parts of this application and just stumbled across this as well wanting to post it here. I should've checked beforehand :D

**Comment by jklmnn** [comment]
Bonn is currently broken. We could integrate https://github.com/publicplan/ParkAPI/commit/38c8fe6303b6283ce75cde7952005a8a15acfc56 since they seem to have it fixed. Yet we need to strip away the parts that are not part of the scraper.

**Comment by jklmnn** [comment]
@Mechtecs is Bonn currently actively maintained by you (or your team)? If so we'd probably like to integrate the fixes you do. Also we could then set Bonn to active support and make it available by default in the apps.

**Comment by Mechtecs** [comment]
Yes it is mostly actively maintained, because we have to use the Bonn API over parkapi.

**Comment by jklmnn** [comment]
Fixed by merging #171.
