### ISSUE TITLE
Frankfurt is broken

### ISSUE THREAD

**Issue by jklmnn** [offenesdresden/ParkAPI#153]
Frankfurt seemed to have its xml url changed to http://offenedaten.frankfurt.de/dataset/912fe0ab-8976-4837-b591-57dbf163d6e5/resource/48378186-5732-41f3-9823-9d1938f2695e/download/parkdatendyn.xml
Also the xml seems to have changed, simply replacing the url didn't work.
@stepan-romankov

**Comment by stepan-romankov** [comment]
@jklmnn ok. I'll take a look on Monday. Thanks for some hints.

**Comment by jklmnn** [comment]
It seems the old url is active again, at least we get current data.

**Comment by jklmnn** [comment]
```
Failed to scrape 'Frankfurt am Main': 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/park_api/park_api/scraper.py", line 90, in main
    scrape_city(module)
  File "/home/park_api/park_api/scraper.py", line 76, in scrape_city
    data = add_metadata(module.parse_html(get_html(city)))
  File "/home/park_api/park_api/cities/Frankfurt.py", line 31, in parse_html
    lot_free = int(tr.find("totalnumberofoccupiedparkingspaces").text)
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by jklmnn** [comment]
After being fixed for a while this issue appeared again. @stepan-romankov is someone working on the API?

**Comment by jklmnn** [comment]
It's currently working so I close this for now.

**Comment by jklmnn** [comment]
The certificate seems to be rejected by python requests:
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='offenedaten.frankfurt.de', port=443): Max retries exceeded with url: /dataset/912fe0ab-8976-4837-b591-57dbf163d6e5/resource/48378186-5732-41f3-9823-9d1938f2695e/download/parkdatendyn.xml (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
```

**Comment by jklmnn** [comment]
It seems that the requests certificate stack doesn't accept the server certificate. Using the system certificate bundle doesn't seem to work either. However any other application seems to accept the certificate.
@stepan-romankov do you have any idea how to fix this?

**Comment by jklmnn** [comment]
Also because of Frankfurt our CI fails as it downloads data from within the module. This leads to the tests requiring online data which makes them fail due to the invalid certificate.

**Comment by hbruch** [comment]
Frankfurt currently does not publish parking data via DATEXII, see https://github.com/ParkenDD/ParkAPI2-sources/issues/2

**Comment by jklmnn** [comment]
I will close this in favor of https://github.com/ParkenDD/ParkAPI2-sources/issues/2. I don't see any reason to keep the discussion in two separate issues and it certainly won't be fixed in this repository.
