### ISSUE TITLE
Python version.

### ISSUE THREAD

**Issue by jklmnn** [offenesdresden/ParkAPI#16]
Shouldn't we just go on with Python 3 and stay clean there?

**Comment by kiliankoe** [comment]
All of this is Python 3.

**Comment by jklmnn** [comment]
Shouldn't we say this somewhere in the Readme?

**Comment by kiliankoe** [comment]
It does ;)

> To get this running locally you'll need Python 3.x and pip installed.

**Comment by jklmnn** [comment]
I should open an Issue on myself: fix blindness.
