### ISSUE TITLE
Fix find_all for beautifulsoup 4.6.0

### ISSUE THREAD

**Issue by jklmnn** [offenesdresden/ParkAPI#166]
For Hamburg `soup.find('wfs:featurecollection').find_all('gml:featuremember')` returns a correct list for beautifulsoup 4.5.3 but an empty list for 4.6.0. I have not yet examined this further so this could either be a bug in how we use `find_all` or a bug in beautifulsoup.
`soup.find('wfs:featurecollection')` alone seems to return the correct data.

cc @kiliankoe @Mic92

**Comment by hbruch** [comment]
This was an [issue](https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/revision/466) in beautifulsoap 4.6.0 which is fixed now. I successfully tried with 4.6.1 and the current 4.7.1.
