### ISSUE TITLE
Is it possible to install ParkAPI in Mac OS X ?

### ISSUE THREAD

**Issue by Manu1400** [offenesdresden/ParkAPI#168]

**Comment by kiliankoe** [comment]
Afaik there's no blockers and it should all work, although it's not explicitly supported to run this on macOS Server (especially since Apple doesn't really support that anymore).

I hack on this application from macOS and run everything on that platform :P

**Comment by Manu1400** [comment]
I don't use macOS Server.

It's possible to have a (only) script who install python, all dependencies, download ParkAPI source code, install Postgres, do all thinks and run the server ?

Thanks you for your works.

**Comment by kiliankoe** [comment]
Besides putting together a Dockerfile and a docker-compose.yml for the application I don't think having a setup script for the application and necessary dependencies is a feasable undertaking. After getting a bit further with #167 I will definitely (finally) handle the docker setup. 

I'm going to go ahead and close this for now. #103 should be the relevant tracking issue for cross-platform deployment.
