### ISSUE TITLE
Transform to current API.

### ISSUE THREAD

**Issue by jklmnn** [offenesdresden/ParkAPI#17]
Transform to current API as described at http://jkliemann.de/parkendd/dev.html

**Comment by kiliankoe** [comment]
What's missing is the list of regions for Dresden and Ingolstadt, right? But this is something we should talk about next week as well.

**Comment by kiliankoe** [comment]
Oh and of course all the required attributes for single lots, but that's going to be rather difficult 😕

**Comment by jklmnn** [comment]
Nope, much more important is the metadata. That should be put out if / is acquired.
See http://jkliemann.de/parkendd/app/

**Comment by kiliankoe** [comment]
Closing this as we've agreed on the spec in the wiki.
