### ISSUE TITLE
Missing steps in setup documentation

### ISSUE THREAD

**Issue by hbruch** [offenesdresden/ParkAPI#186]
I followed the setup instructions, but needed to perform some additional steps which are not documented yet (perhaps I missed something in the docs?):

* I had to copy config_example.ini and adapt it
*  python -m unittest discover tests required a running Postgres db (did not expect this for unittests) and threw exceptions as the testing database had no tables (I set env=testing and ran parkapi-setupdb to work around this)

**Comment by jklmnn** [comment]
The configuration and some setup steps are indeed not documented, see #79. Due to time limits a proper documentation will be missing for a while in the future.

The tests, and especially the `live_scrape` option shouldn't depend on a database. Yet I currently can't say why they do.

**Comment by kiliankoe** [comment]
I'll try to make an effort to streamline and document the setup process for the new version 👍

**Comment by defgsus** [comment]
Hi there, had the same problem (#229). 
The docs are updated now
