### ISSUE TITLE
Provide DATEX II German profile importer

### ISSUE THREAD

**Issue by hbruch** [offenesdresden/ParkAPI#189]
I suggest to provide a generic DATEX II parser for the German profile "MDM Datenmodell für städtische Parkierungseinrichtungen" (currently V 00-01-03). The Frankfurt-Parser might be a good start for this.

DATEX II defines (amongst others) a data model dedicated to parking which is gaining interest, as German cities start publishing their parking data via the portal Mobilitätsdatenmarktplatz (MDM).

According to the specification lead Jörg Freudenstein, the German profile "MDM Datenmodell für städtische Parkierungseinrichtungen-V00-01-03 is based on the DATEX II 2.0 parking extension (see [attachment](https://github.com/offenesdresden/ParkAPI/files/3157641/MDM_Datenmodell_Parkierung_00-01-03.zip) provided by Jörg Freudenstein).

Though the parking extension was integrated (and extended) in the official DATEXII V2.3 and will see further changes with V3.0, the German profile is not yet updated and still in use by German cities (Frankfurt, Düsseldorf, Kassel (see #184)) or planned to use (Stuttgart (see #36), Karlsruhe).

**Comment by jklmnn** [comment]
I moved this into version project 1.1. While we probably need this earlier it should be a definite long term feature after the restructuring.

**Comment by kiliankoe** [comment]
This is fantastic, but will definitely be influenced by (and also influence) the work I'm currently putting into restructuring the application. Thanks for the issue, I'll definitely be coming back to this!

**Comment by hbruch** [comment]
Closing here to continue discussion in https://github.com/ParkenDD/ParkAPI2-sources/pull/21
