### ISSUE TITLE
[Mannheim] Data

### ISSUE THREAD

**Issue by kiliankoe** [offenesdresden/ParkAPI#208]
https://mobileapps.ffh.de/iphone/parkhaeuser/parkhaeuser.json?city=mannheim

**Comment by jklmnn** [comment]
Mannheim is already available, although I didn't check if it uses this source: https://github.com/offenesdresden/ParkAPI/pull/205.

**Comment by kiliankoe** [comment]
Ah, you're right. And it doesn't, it uses https://www.parken-mannheim.de, which is probably *more official*.
