### ISSUE TITLE
city_schema.json outdated(?)

### ISSUE THREAD

**Issue by hbruch** [offenesdresden/ParkAPI#219]
I just took a closer look into `city_schema.json`, trying to validate Herrenberg ParkAPI output against it. It seems to me that this schema is completely outdated and does not match the current interface any longer (`coords` are nested in the API, but flat in schema, `count` is named `total` and some further differences). Am I wrong to suppose it should validate the output of a city request like e.g. https://api.parkendd.de/Ulm?

**Comment by jklmnn** [comment]
This schema is indeed outdated. I have a status repository that I use to check the API status which currently validates all cities. We have to update the specs in this repository. In the meantime you can use https://github.com/jklmnn/parkendd-status/blob/master/schema_city.json (although the API might contain fields that are not present in this schema).

**Comment by jklmnn** [comment]
Is this solved for you with #220?

**Comment by hbruch** [comment]
Indeed, it is.
