### ISSUE TITLE
Update python

### ISSUE THREAD

**Issue by jklmnn** [offenesdresden/ParkAPI#222]
Python 3.5 does not support f strings which some of our dependencies need in newer versions. Since even Debian Stable has Python 3.7 support we should upgrade the compatibility to Python 3.7 and newer.

**Comment by hbruch** [comment]
What need's to be done:

- [ ] Bump Dockerfile base image version
- [ ] Adapt travis-job
- [ ] Update setup.py classifiers Programming Language
