### ISSUE TITLE
Konstanz scraper collects bogus data

### ISSUE THREAD

**Issue by defgsus** [offenesdresden/ParkAPI#232]
Currently, looking at `https://api.parkendd.de/Konstanz` it show things like this for every lot:
```json
{
  "address": null,
  "coords": null,
  "forecast": false,
  "free": 0,
  "id": "konstanz168",
  "lot_type": null,
  "name": "168",
  "state": "nodata",
  "total": 0
}
```

I haven't looked into the details as i actually just rewrote the scraper for [ParkAPI2](https://github.com/defgsus/ParkAPI2). [Their website](https://www.konstanz.de/start/leben+in+konstanz/parkleitsystem.html) is working fine.

I guess they changed the number of columns in the tables and what once was the lot name is now the number of free spaces. You will probably notice when exporting the archive for 2021 ;)

**Comment by defgsus** [comment]
Checking my own little scraper, the change in the table has been [some months ago](https://github.com/defgsus/parking-scraper/commit/c9a0dd04ed06193a24402a9dec5bd25b6adaf558).

**Comment by jklmnn** [comment]
I see, thanks for noticing. The reason for that is likely that we had to make the scraper more error resistant (sometimes single lots would have missing information). However we only check if the scraper fail. So as it was error resistant it didn't fail anymore on missing data.
