### ISSUE TITLE
Wiesbaden: again?

### ISSUE THREAD

**Issue by AugustQu** [offenesdresden/ParkAPI#240]
Hi,

heute gab es in der Lokalzeitung einen Artikel zum Thema Parkleitsystem, aufgebaut von der Stadt. Und es funktioniert nicht richtig.

Da habe ich mir mal die Zeit genommen und die Internetseite der Stat durchsucht. Folgende Seite habe ich gefunden: https://geoportal.wiesbaden.de/parkleitsystem/parkhaeuser.php

Dies könnte man doch als Basis nehmen. Soll ich?

Schönen Gruß
AugustQ

**Comment by jklmnn** [comment]
Das sieht gut aus als Quelle. Ja leider gehen immer wieder Quellen kaputt bzw. ändern sich und mir fehlt es leider an der Zeit das immer zu fixen.

**Comment by jklmnn** [comment]
Du kannst es aufbereiten wie gehabt. ParkAPI2 läuft zwar schon parallel aber ich weiß nicht ob und wann ich die Zeit finde alles auf eine Platform zu ziehen.

**Comment by AugustQu** [comment]
ich habe meine Anpassungen vorgenommen und einen pull-request erstellt.

Getestet habe ich dies leider nur in meiner Umgebung. Ich hoffe, daß ich bei der Übertragung auf die Umgebung hier keinen Fehler eingebaut habe. Und: den Zugriff auf das JSON-file kann ich bei mir nicht testen.

**Comment by AugustQu** [comment]
funktioniert meine Lösung? Hattest Du die Zeit, meine Lösung zu testen?

Schönen Gruß
AugustQ

**Comment by AugustQu** [comment]
Funktioniert es? Sobald es wieder auf der Karte/in der App verfügbar ist, schreibe ich etwas auf meinem Blog dazu.

PS: ich komme aber erst nach Weihnachten dazu.

**Comment by jklmnn** [comment]
Sieht aus als ob es wieder geht: https://parkendd.de/map.html#Wiesbaden

**Comment by AugustQu** [comment]
ich habe mal etwas dazu geschrieben: https://linux-fuer-wi.blogspot.com/2023/01/parkendd-neuer-versuch.html

Mein Text ist eigentlich eine Kritik an der Lösung der Stadt Wiesbaden. Diese Lösung ist nicht brauchbar, denn der Anwendungsfall ist ein Autofahrer, der in die Stadt fährt und dort einen Parkplatz sucht. Er wird nicht auf der Seite der Stadt Wiesbaden diese Information suchen und dann in der Grafik jedes Parkhaus einzeln abfragen. 

Handy-Nutzung währed des Autofahrens ist strafbar. Aber die Stadt Wiesbaden hat nicht vom Anwendungsfall gedacht, als sie diese Software entwickelt haben.

**Comment by AugustQu** [comment]
ich hatte auch schon mal so eine Idee. Eigentlich müsste man die Daten auf dem Display des Autos sehen, nicht auf dem Smartphone. 

Nun ist dies alles neu für mich, denn ich habe noch nie Software für Anddorid (oder gar Android car) geschrieben. Aber ParkenDD war für mich auch völlig neu .....

Problem: ich habe keine Testmöglichkeit, denn ich fahre einen Tesla. Dies ist dann insbesondere kein Andorid.

Mal lesen.

**Comment by jklmnn** [comment]
Bevor du da viel Arbeit reinsteckst: ich habe ehrlich gesagt nicht mehr die Zeit das Projekt richtig zu maintainen. Ich schau mir hin und wieder eine kaputte Stadt, halte den Server aktuell oder manage PRs, aber mehr schaffe ich nicht. Das Projekt läuft so lange wie es damit läuft aber sollte mal irgendwas essentielles kaputt gehen, werde ich das nicht mehr fixen.

Deshalb bin ich auch nicht in der Lage so signifikante Änderungen wie beispielsweise eine Fahrzeugintegration richtig zu integrieren und ich kann auch nicht versprechen, dass es ewig laufen wird. Ich habe bereits damit angefangen andere Leute aus der OpenData Community zu suchen, die es weiterführen könnten, bis jetzt leider noch ohne Erfolg.

Bis dahin wird das Projekt soweit es geht ohne große Änderungen weiterlaufen.
