### ISSUE TITLE
[Lübeck] Data

### ISSUE THREAD

**Issue by kiliankoe** [offenesdresden/ParkAPI#3]
http://www.kwl-luebeck.de/parken/aktuelle-parkplatzbelegung/

**Comment by kiliankoe** [comment]
More or less done in eb723da844b9502d71fbb12f9fb0c2df3545a6ac

The only thing missing would be the state for the lots without any numbers. I can currently see `Geöffnet` and `Vorübergehend geschlossen`.

**Comment by florianschmidt1994** [comment]
Alternative URL http://www.kwl-luebeck.de/app/module/externalsource/get
