### ISSUE TITLE
[Karlsruhe] Data

### ISSUE THREAD

**Issue by kiliankoe** [offenesdresden/ParkAPI#33]
http://vmz.karlsruhe.de/entry-tba_Parkleitsystem/

Data is displayed when a lot is selected

**Comment by florianschmidt1994** [comment]
http://vmz.karlsruhe.de/entry-tba_Parkleitsystem/nullsearch?form=nullform

**Comment by AugustQu** [comment]
https://web1.karlsruhe.de/service/Parken/

sieht machbar aus.

ABER:

im HTML gibt es einen Eintrag:
`</div><strong><a href="https://web1.karlsruhe.de/service/Parken/detail.php?id=N06">Kreuzstraße (C&amp;A)</a></strong><br>`

BeautifulSoup macht daraus:
`</div><strong><a href="detail.php?id=N06">Kreuzstraße (C&amp;A;)</a></strong><br/>`

d.h.:
aus (C&amp;A) wird (C&amp;A;)
sodaß der Name erscheint als: Kreuzstraße (C&A;)

Wie behandelt man das?

**Comment by AugustQu** [comment]
(C&A):
das ist ein Problem mit BeautifulSoup.
Version 4.6.0 produziert das beschriebene Problem
Version 4.7.1 macht es richtig.

**Comment by jklmnn** [comment]
This is fixed by https://github.com/offenesdresden/ParkAPI/commit/0f4ced6e2e5e7fcc4fb0f269a92a55964d3ebf39. The working version of bs4 is available through pip. I just have to remember to update the server.
