### ISSUE TITLE
[Stuttgart] Data

### ISSUE THREAD

**Issue by kiliankoe** [offenesdresden/ParkAPI#36]
http://verkehrslage.stuttgart.de/ivl/app.html?map=ilvLos&layers=Raster,LOS,&overlay=default&extents=3512167,5403934,3514138,5405312

**Comment by florianschmidt1994** [comment]
Als erster Anfang: http://verkehrslage.stuttgart.de/ivl/ivlParkraumOverlay.php Liefer Koordinaten und einen Link zu einem Bild, aus dessen Namen man relativ einfach den Status erkennen könnte. Was fehlt, sind Namen der Parkhäuser und weitere Infos

**Comment by hbruch** [comment]
Über ivlParkraumOverlay.php kann für jedes Parkhaus/-platz mit http://verkehrslage.stuttgart.de/ivl/prinfo/_<id>.html eine Detailseite mit Detailangaben zur Belegung und Name ermittelt werden. Ich werde anfragen, ob die ivlx nicht auch eine Seite bereitstellen kann, die alle Angaben gesammelt bereitstellt.

**Comment by hbruch** [comment]
Nach Anfrage bei IVLZ folgende Infos: Die IVLZ befindet sich gerade in der Umstellung auf eine Datenbereitstellung via Mobilitätsdaten-Marktplatz (MDM). Diese ist für in ca. 2 Monaten geplant. Ich habe mich als Beta-Tester registriert.

**Comment by kiliankoe** [comment]
Danke für die Infos! Ich höre gerade zum ersten Mal vom MDM, sieht ja "interessant" aus 🙈

**Comment by hbruch** [comment]
Karlsruhe plant ebenso eine Bereitstellung via MDM ab 2020. Vermutlich macht ein generischer DATEXII-Parser Sinn (die Frankfurt.py-Implementierung dürfte recht übertragbar sein). Und wahrscheinlich wäre es auch ein Einfaches, DATEXII als zusätzliches Ausgabefomat für ParkAPI umzusetzen.

**Comment by jklmnn** [comment]
Ich bin mir nicht sicher ob ich MDM gut finden soll. Alleine die Tatsache, dass man sich einloggen muss um die URL zu den Daten zu bekommen ist ein riesiges Red Flag. Wenn du registriert bist, kommst du an die URLs bzw. Daten heran? Ich hab die Befürchtung dass das alles so closed wird, dass es für Open Data vollkommen nutzlos ist.

**Comment by kiliankoe** [comment]
Die Existenz vom MDM ändert ja nichts daran, dass wir die Daten weiterhin so bereitstellen wie wir es aktuell tun. Daten aus mehr Quellen einzulesen ist generell auch nicht falsch und wenn wir sie in weiteren Formaten bereitstellen können, die einen Mehrwert bieten, dann seh ich auch da kein Problem.

**Comment by kiliankoe** [comment]
> Vermutlich macht ein generischer DATEXII-Parser Sinn (die Frankfurt.py-Implementierung dürfte recht übertragbar sein).

Das klingt ja auch klasse. Aktuell sind die Parser alle auf spezifische Städte zugeschnitten. Wäre super, wenn's da schon Gemeinsamkeiten gibt, die das vereinheitlichen.

**Comment by sibbl** [comment]
Um vielleicht ein paar kurze Einblicke aus meiner Arbeitswelt zu geben: der MDM und auch die mCloud sind zwei Datenplattformen, die das BMVI seit geraumer Zeit stark vorantreibt. Der [MDM](https://service.mdm-portal.de) ist eher für dynamische Daten gedacht, die [mCloud](https://www.mcloud.de/) für statische.

Bei allen vom BMVI geförderten Forschungsprojekten wird ein besonderes Augenmerk darauf gelegt, dass die Ergebnisse und Daten nach Projektlaufzeit der Öffentlichkeit bereitgestellt werden. Da das nicht immer geht, soll zumindest das Ziel sein, dass projektübergreifend ein Mehrwert daraus entstehen kann - letztendlich fließen ja auch nicht wenige Steuergelder da rein.

Erfahrungsgemäß läuft das in den Projekten dann so ab, dass die Projektpartner mit den Daten (meist Städte sowie Firmen) das auch von Beginn an machen wollen, aber oft das technische Know-How fehlt und mindestens eine Person Datenschutzbedenken hat. Das BMVI stellt allerdings gute Beratungsmöglichkeiten bereit und veranstaltet einige Hackathons (zuletzt der BMVI Data Run im März), um den Firmen die Angst zu nehmen und zu zeigen, was Leute da draußen mit den Daten anstellen.

Letztendlich ermöglicht das Login aber eben auch eine Art Paywall - heißt ja auch Marktplatz. Dateninhaber können Zugriff auf ihre Datenströme verkaufen. Teilweise fließen dort auch größere Datenmengen von 10 MB pro Sekunde und mehr, wo man halt auch bedenken muss dass eine kostenlose und offene Bereitstellung nicht für jeden Datenanbieter rentabel ist.

Im Parkplatz-Kontext denke ich aber, dass gerade ParkenDD aber sogar helfen kann, dass die Daten dann eben nicht mehr hinter einem Login stehen. DATEX II zu unterstützen wäre ein wichtiger Schritt. Wie oben schon geschrieben, ist dieser eigentlich sehr umfangreiche Standard in diesem Kontext nicht all zu komplex.

**Comment by kiliankoe** [comment]
Danke für den Einblick, @sibbl! Gut zu wissen, dass wir noch jemanden als Ansprechpartner haben, der da etwas weiter drinsteckt 😜

**Comment by hbruch** [comment]
@sibbl Weißt Du, welchen Status die anscheinend für deutsche Kommunen angestrebte Ableitung "MDM Datenmodell für städtische Parkierungseinrichtungen" derzeit hat? Ich finde aktuell nur die noch sehr frühe Version [00-01-03](http://2015.bmvi-data-run.de/datensaetze/dateien/MDM-Datenmodell_Parkierungseinrichtungen_00-01-03.pdf)... (Aber vielleicht machen wir zu DATEXII Import/Export besser einen eigenen Issue auf...)

**Comment by hbruch** [comment]
Heute kam nochmal diese Antwort auf meine Email-Anfrage an IVLZ:

„Das Parkleitsystem erfährt derzeit eine grundlegende Erneuerung. Der Bau des neuen Systems dauert bis Mitte 2020. In absehbarer Zeit wird deshalb des System für den Neubau komplett ausgeschaltet. Dann wird auch auf der Homepage keine Anzeige mehr erfolgen.

Mit dem neuen System werden die dynamischen Daten über den Mobilitäts Daten Marktplatz der Bundesanstalt für Straßenwesen übertragen und bereit gestellt. Über diesen können Sie dann die Daten ebenfalls erhalten und in Ihre Systeme einbinden.

Deshalb müssen wir Sie da nun etwas vertrösten bis das neue System hergestellt ist.
Dann ist eine Einbindung auch zielführender möglich.“

**Comment by hbruch** [comment]
Stuttgart in the meantime publishes it's parking data via the MDM. 

I suggest closing this discussion here and continue it here: https://github.com/ParkenDD/ParkAPI2-sources/pull/21

**Comment by jklmnn** [comment]
> I suggest closing this discussion here and continue it here: https://github.com/ParkenDD/ParkAPI2-sources/pull/21

Sounds good to me.
