### ISSUE TITLE
<city>.py bad defined variables

### ISSUE THREAD

**Issue by RobTranquillo** [offenesdresden/ParkAPI#51]
the vars 
data_url = ""
data_source = ""
city_name = ""
file_name = ""
detail_url = ""
are a little bit redundant. Please make more clear by name whats the use for every single var or set an comment

**Comment by kiliankoe** [comment]
I tried explaining them inside the Sample City file, but that's slightly outdated as of today. But you're right, that stuff should definitely be added to [Adding support for a new city](https://github.com/offenesdresden/ParkAPI#adding-support-for-a-new-city) in the readme as well.

 - `data_url` is the URL of the content loaded by the scraper
 - `data_source` is a source URL that can be displayed in the app where the data is coming from, usually the base domain or maybe more specific than that
 - `city_name` is the real name of the city (e.g. Dresden or Lübeck)
 - `file_name` is the name of the city file without the ending (e.g. Dresden or Luebeck). This can probably be removed in favor of using `__file__` but is needed by the scraper nonetheless.
 - `detail_url` is not used at the moment and was only an early experiment for Dresden. It'll maybe become relevant sometime in the future. The idea was to provide the rest of the URL to be able to scrape detail pages from single lots.

**Comment by kiliankoe** [comment]
Is this ok in it's current form? Everything should be explained in `Sample_City.py` and the readme has gotten a bit more specific about how to add a new city.
