### ISSUE TITLE
500 internal error occurs when sending a request without user agent header

### ISSUE THREAD

**Issue by sibbl** [offenesdresden/ParkAPI#73]
Is this by design so we can track clients?

**Comment by kiliankoe** [comment]
Umm... No. User agents are logged for statistical reasons (even though caching through nginx and cloudflare will render this somewhat obsolete), but of course it shouldn't die when it isn't sent. Oops :D

**Comment by sibbl** [comment]
Still throws a 500 on all endpoints but /<city_id>. Needs some copy-and-pasting I guess.
