### ISSUE TITLE
Active support?

### ISSUE THREAD

**Issue by kiliankoe** [offenesdresden/ParkAPI#75]
I'm guessing we're going to have to go ahead and more or less actively support adjusting the scraper if any of the data sources of the cities we offer data for change. Either we do this or expect to ruin user experience if anything dies and we don't care about fixing it for days/weeks.

This seems to be happening rather often and the list of cities we're already supporting isn't short. Either we're clear about not offering data every now and then (and presumably getting bad app reviews at that point) or we try our best supporting stuff.

I'm opening this issue to discuss this. An option would of course also be to remove already added cities (for now) and focus on those we actually want to continuously support. I'm thinking Dresden (obviously), Ingolstadt (I'd do that) and Zürich (as they actually offer machine-readable data \o/). Anything else would have to wait for people offering their help.

Comments or ideas?

**Comment by jklmnn** [comment]
Focusing on Dresden and Zürich might be a good start. I have an interest to publish the new apps soon ;)

**Comment by kiliankoe** [comment]
Also how would we go about testing new cities without giving all users access to them? Keep them out of the meta list or create a staging server? @Mic92 any thoughts?

**Comment by Mic92** [comment]
We need some way to show, that we had actually a working solution for a city, so in case some local coder wants to support it long term. Maybe a list with cities and who is the current maintainer. In any way, if the scraper is working we should collect the data and make it downloadable.

**Comment by Mic92** [comment]
I would not create a different server for that, maybe not show them up in the user interface or with a warning. Does the app store description point to this project?

**Comment by kiliankoe** [comment]
> Maybe a list with cities and who is the current maintainer.
I was thinking about handing single scrapers over to local OK labs (if they exist), so yeah, definitely an option. Adding that to the README or another document here is a great idea.

> In any way, if the scraper is working we should collect the data and make it downloadable.
Sure, but maybe not offer it to the mobile apps as supported cities but only for those that want the data? A different endpoint or something else?
Or an in-app warning like you say.

> Does the app store description point to this project?
Not yet, but it will.

**Comment by kiliankoe** [comment]
An easy option would (as @Mic92 already suggested) to just filter them on the client side. The easiest option to go about this without having to push new app updates would be to add an `active_support` bool property to the cities in the metadata. Wouldn't make much of a difference, but that way we don't have to filter out any cities, are offering all data for interested parties and offer up anything where a scraper seems to be working. Would that be an option? @offenesdresden/parkendd

**Comment by jklmnn** [comment]
:+1: 
Then we could also add a switch in the App so people living in cities without active support could use them but still would know that there can be problems.

**Comment by kiliankoe** [comment]
Would definitely be a possibility.

**Comment by kiliankoe** [comment]
:heavy_check_mark: 841da9ae4dbe49fde10f3c431798ef637157ae39
