### ISSUE TITLE
Move db json field to single table rows

### ISSUE THREAD

**Issue by kiliankoe** [offenesdresden/ParkAPI#76]
We are looking at pretty much standardized data here. Not a lot is gained by saving data directly as json. Let's dump this for a more traditional layout.

**Comment by Mic92** [comment]
+1

**Comment by kiliankoe** [comment]
Forecasts are still missing, the rest already looks **much** better in #167.

**Comment by jklmnn** [comment]
Database issue, any further discussion about this in #167.
