### ISSUE TITLE
Cache latest results

### ISSUE THREAD

**Issue by kiliankoe** [offenesdresden/ParkAPI#77]
@Mic92 

What about a separate db table for storing a largest known number and we'd only check the latest entries and update this largest value? Would that work?

**Comment by Mic92** [comment]
Yes, that was what I have meant by using [procedures](http://www.postgresql.org/docs/9.3/static/plpgsql-trigger.html)

**Comment by kiliankoe** [comment]
Currently implemented as a materialized view in #167.

**Comment by jklmnn** [comment]
Database issue, any further discussion in #167.
