### ISSUE TITLE
Document config.

### ISSUE THREAD

**Issue by jklmnn** [offenesdresden/ParkAPI#79]
Document config file.

**Comment by kiliankoe** [comment]
?

**Comment by jklmnn** [comment]
Just by looking at the config it is not self explanatory what some keys mean.

**Comment by kiliankoe** [comment]
Ah, I just had no idea what this issue was about :D

**Comment by jklmnn** [comment]
Is this still active? Otherwise I would close it.

**Comment by kiliankoe** [comment]
Closing this, let's see what kind of config we end up with for the new version 🙈
